version: '3'

services:
  node-serve-front:
    image: llinkedlist/python-rev-front:v1
    ports:
      - "5000:5000"
      - "1145:1145"
    volumes:
      - .:/workspace
    restart: unless-stopped
    command: ["python", "/workspace/main.py", "--port", "1145", "--host", "0.0.0.0"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  streamlit-front:
    image: llinkedlist/python-rev-front:v1
    ports:
      - "5001:5000"
    volumes:
      - .:/workspace
    restart: unless-stopped
    command: ["streamlit", "run", "/workspace/front_python/front_manager.py", "--server.port", "5000", "--server.headless", "true", "--server.address", "0.0.0.0"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local 