version: '3'

services:
  node-serve-front:
    image: llinkedlist/python-rev-front:v1
    ports:
      - "5000:5000"
      - "1145:1145"
    volumes:
      - .:/workspace
    restart: always
    command: >
      sh -c "streamlit run /workspace/front_python/front_manager.py --server.port 5000 > streamlit_log.txt 2>&1 & &
             python /workspace/main.py --port 1145"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local