version: '3'

services:
  node-serve-front:
    image: llinkedlist/python-rev-front:v1
    ports:
      - "5000:5000"
      - "1145:1145"
    volumes:
      - .:/workspace
    restart: always
    command: >
      sh -c "streamlit run /workspace/front_python/front_manager.py --server.port 5000 &
             python /workspace/main.py --port 1145"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
    driver: local