version: '3'

services:
  node-serve-front:
    image: llinkedlist/python-rev-front:v1
    ports:
      - "5000:5000"
      - "1145:1145"
    volumes:
      - .:/workspace
    restart: unless-stopped
    command: ["bash", "/workspace/start_services.sh"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1145/api/v1/clients_status", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
    driver: local